### ISSUE TITLE
Need update to support selenium 2.45.x

### ISSUE THREAD

**Issue by tedlandis** [pytest-dev/pytest-splinter#21]
Latest Firefox (v36) requires selenium 2.45+

**Comment by bubenkoff** [comment]
pytest-splinter doesn't pin any of it's dependencies
and i just checked (again) - it just works with the latest selenium with no problem
splinter 0.7.0 pins selenium version strictly to the 2.44, not sure why exactly - so that's probably why you've created this issue
in paylogic setup we still use selenium==0.6.0 where selenium is not pinned so strictly

**Comment by tedlandis** [comment]
Thanks, sorry for bugging the wrong team. :)
Either way, splinter has now been upgraded to support 2.45 so everything runs again.
